name: Sync timetable and publish iCalendar

# This workflow runs on a schedule (every 10 hours) and on demand via the
# `workflow_dispatch` event. It synchronises the user's school timetable and
# publishes a fresh `docs/edt.ics` file, which can then be served via
# GitHub Pages. Customize the cron expression to change the frequency.
on:
  schedule:
    # Runs at minute 0 every 10th hour (i.e. 00:00, 10:00, 20:00 UTC)
    - cron: '0 */10 * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar pytz

      - name: Run synchronisation script
        run: python sync_script.py
        env:
          USERNAME: ${{ secrets.ENT_USERNAME }}
          PASSWORD: ${{ secrets.ENT_PASSWORD }}
          LOGIN_URL: ${{ secrets.ENT_LOGIN_URL }}
          EVENTS_URL: ${{ secrets.ENT_EVENTS_URL }}

      - name: Commit updated calendar
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add docs/edt.ics
          git commit -m "Update calendar (auto)" || echo "No changes to commit"
          git push